### ISSUE TITLE
Example Exchange Set for comment

### ISSUE THREAD

**Issue by TomRichardson6** [iho-ohi/S-101-Test-Datasets#1]
All, 

In readiness for further discussions I wanted to share an example S-100 Exchange Set which although it includes S-101 and S-102 datasets. IC-ENC now has a tool which allows us to generate S-100 Exchange Sets and this may be useful in supporting this work of this group. The Exchange Set simply uses dummy signatures so those should be ignored. 

I would welcome any comments on the structure of the exchange set and content of the Catalog.xml provided here. Please ignore the datasets at this stage. 

[30c8098d-d886-4a7f-ad13-08a8299de281.zip](https://github.com/iho-ohi/S-101-Test-Datasets/files/7847795/30c8098d-d886-4a7f-ad13-08a8299de281.zip)

**Comment by IngaFjellanger** [comment]
Hi,
About Catalog.xml:
It says it is: _Based On: "Part XX Discovery Metadata and Exchange Catalogues_5.0.0_Draft_Redline+07192021.doc"_
I could not find that version of the Part XX document, so I have used the most recent version I have , the one we got for the S-100WG6, _Part XX Discovery Metadata and Exchange Catalogues_5.0.0_Draft_Redline_21122020 Cleaned up.doc_  . Several changes were added during the S-100WG6, but I do not have an updated version.
I note that there must have been some changes done between the 2 versions of Part XX. So I have also compared with official version of S-100 edition 4 .
The general impression is that there is so many changes that I will not use time on continuing investigating. I will only give some impressions based on investigating the beginning.
- Should empty tags like <S100XC:exchangeCatalogueComment /> be included? It could be omitted since it is not mandatory.
-  dateTime is encoded like **<S100XC:dateTime>20220110T110843Z</S100XC:dateTime>** which is correct according to my version of Part XX. All the other times dates and times are encoded it is done like e.g.: **<S100XC:date>2018-12-01</S100XC:date>**  and **<S100XC:issueTime>00:00:00-05:00</S100XC:issueTime>**  The last way of encoding dates and times are according to what was decided during S-100WG6 .

**Comment by TomRichardson6** [comment]
Inga, thanks for your input, this tool is based on a pre S-100WG6 draft and therefore does not reflect changes posted there. I understand that its not useful to assess at this time but once a stable draft is available the tool will be updated and I will seek to upload a further exchange set for assessment against that draft.

**Comment by rmalyankar** [comment]
The S-100 metadata subgroup is still making changes to metadata for S-100 5.0 and the S-100 generic schemas will be updated after that is complete...

**Comment by DavidGrant-NIWC** [comment]
Recommend close as OBE - unable to load the catalog because it doesn't conform to the 5.0 schema.

**Comment by TomRichardson6** [comment]
Closed as OBE
