### ISSUE TITLE
CATALOG.XML missing navigationPurpose

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Test-Datasets#17]
The datasetDiscoveryMetadata has "Transit" encoded in specificUsage, but does not encode "transit" for navigationPurpose. If only one value is encoded then navigationPurpose should take precedence.

**Comment by kusala9** [comment]
another one caused by importing old edition 4.0.0 exchange sets and leaving the data unchanged. What does the ECDIS actually "require" here? The version 2.0 exchange set has neither specificUsage nor navigationPurpose as they're not required by the schema. If one is actually required we should clarify either through the schema or in S-98 (as they're likely only to be for ENC).

**Comment by kusala9** [comment]
it's fine for S-101 to require navigation purpose - if it is **Required** on the ECDIS then it needs to be clarified in S-98 that it will be present in the CATALOG.XML and what's it's needed for. Otherwise it will be left out of the S-164 exchange sets. Either way, this can be closed - re-raise in S-98 for clarification on what it's for on the ECDIS if required, otherwise it's product specification specific and no ECDIS behaviour is required.
