### ISSUE TITLE
CATALOG.XML fileName format incorrect

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Test-Datasets#21]
`S-101\DATASET_FILES\101AA00DS0003.000` specified, should be: `file:/S-101/DATASET_FILES/101AA00DS0003.000`

![image](https://user-images.githubusercontent.com/62906211/212421881-8ef1b411-e70a-46a2-8753-8c53f64ed952.png)

![image](https://user-images.githubusercontent.com/62906211/212422194-a3421d21-ea80-491c-94d2-019ca59d0250.png)

**Comment by kusala9** [comment]
I've changed the revised exchange catalogue to all "/"s but left out the file: prefix for now. I believe fileName is still encoded as a string in the edition 5.0.0 schemas. IF these are genuinely supposed to be URIs then the schemas should reflect this. Otherwise all these strings have to be converted to/from URIs when echange sets are processed which is prone to error. We need to clarify this in Part 17 as well I think, certainly that the file seaprator is "/", that there is a leading one and that the proper URI format is the only one supported.

**Comment by DavidGrant-NIWC** [comment]
It must be a URI:
![image](https://user-images.githubusercontent.com/62906211/212958402-31842909-86f6-4540-91b6-4aab8c1c965a.png)
![image](https://user-images.githubusercontent.com/62906211/212958823-683ced05-c57c-433a-a845-992a7f5c3e62.png)

**Comment by kusala9** [comment]
this can probably be closed. CATALOG.XML can be defined in the S-164 repository leaving this repo to only define the datasets and their supporting resources. CATALOG.XML is useful but not completely necessary. Certainly, the S-164 repo is using the correct format for fileName elements. Suggest no further action in this repo on this, re-raise in S-164 if this is still a problem.
